name: Generate QR 2
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ps42
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - run: npm install -g expo-cli
      - run: npm install
      - run: expo start --tunnel --port 7000 > index.txt
