name: Generate QR
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run App
      - run: npm install -g expo-cli
      - run: npm install
      - run: expo start --tunnel > out.txt &
